
  name: rtsp2ws
  base: core22
  version: git
  summary: RTSP to websocket 
  description: |
    This is a gateway to forward encoded frame received from RTSP/RTP to websocket and then decode using WebCodec.

  grade: stable 
  confinement: strict

  parts:
    rtsp2ws:
      plugin: cmake
      source: .
      source-type: git
      build-packages:
      - g++
      - pkg-config
      - libssl-dev      
      stage-packages:
      - libssl3      

    local-parts:
      plugin: dump
      source: ./config.json
      source-type: local

  apps:
    rtsp2ws:
      command: usr/local/bin/rtsp2ws -p $SNAP/usr/local/share/rtsp2ws/www -C $HOME/config.json
      daemon: simple   
      plugs: 
      - network-bind
      - home
