
  name: rtsp2ws
  base: core22
  adopt-info: rtsp2web
  summary: RTSP to websocket 
  description: |
    This is a gateway to forward encoded frame received from RTSP/RTP to websocket and then decode using WebCodec.

  grade: stable 
  confinement: strict
  license: Unlicense
  contact: michel.promonet@free.fr

  parts:
    rtsp2web:
      plugin: cmake
      source: .
      source-type: git
      build-packages:
      - g++
      - pkg-config
      - libssl-dev      
      stage-packages:
      - libssl3
      override-pull: |
        craftctl default
        craftctl set version="$(git describe --tags --always)"

  apps:
    rtsp2web:
      command: usr/local/bin/rtsp2web -p $SNAP/usr/local/share/rtsp2web/www -C $SNAP_USER_DATA/config.json -c $SNAP/usr/local/share/rtsp2web/keycert.pem
      daemon: simple   
      plugs: 
      - network-bind
      - home
